### ISSUE TITLE
New extension-storage collection will need to be in STANDARD_COLLECTIONS

### ISSUE THREAD

**Issue by thomcc** [mozilla-services/server-syncstorage#128]
(And anywhere else along the same lines). We're working on a sync15-based engine for extension-storage, moving it from Kinto. Probably some (small) number of things might be be desirable to change in this repo to prepare for that, although the only one I know of is stuff like the STANDARD_COLLECTIONS list.

**Comment by rfk** [comment]
@thomcc is "extension-storage" the name of the collection? I vaguely recall us wanting to have two separate-but-related collections in order to work with generic sync.

I put up an initial PR for this in https://github.com/mozilla-services/server-syncstorage/pull/133; there are no other changes that would be required in this repo AFAICT.

**Comment by rfk** [comment]
Per meeting: WONTFIX
