### ISSUE TITLE
Should PUT of invalid BSOId return 400 or 404?

### ISSUE THREAD

**Issue by mostlygeek** [mozilla-services/server-syncstorage#30]
On [this testing line](https://github.com/mozilla-services/server-syncstorage/blob/master/syncstorage/tests/functional/test_storage.py#L930) it says a PUT with an invalid BSO Id should return a 404. Should this be a 400 Bad Request instead?

**Comment by rfk** [comment]
Likely it's a 404 "by accident" because of the way routing works in the webapp - the id is in the URL, so an invalid ID doesn't match the URL routing regex, so it becomes a 404.  I can see arguments for either option being "more correct" than the other, but my default position is to leave well enough alone :-)

**Comment by mostlygeek** [comment]
heh ok.
